[workspace]
resolver = "2"
members = [
    "crates/merdraw-parser",
    "crates/merdraw-layout",
    "crates/merdraw-ascii-render",
    "crates/merdraw-skia-render",
    "crates/merdraw",
    "crates/merdraw-preview",
]
